name: stellar_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.15.0 <4.0.0'


dependencies:
  http: ^1.1.0
  blockchain_utils: ^3.4.0
  # blockchain_utils:
  #   path: ../../bitcoin/blockchain_utils

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  flutter_lints: ^4.0.0
