name: stellar_dart
description: A comprehensive library for interacting with the Stellar network, including support for operations, smart contracts, and wallet management.
version: 0.1.0
homepage: "https://github.com/mrtnetwork/stellar_dart"
repository: "https://github.com/mrtnetwork/stellar_dart"
Author: mrhaydari.t@gmail.com
topics:
  - stellar
  - soroban
  - wallet
  - xlm

environment:
  sdk: '>=2.15.0 <4.0.0'


dependencies:
  http: ^1.1.0
  blockchain_utils: ^3.4.0
  # blockchain_utils:
  #   path: ../../bitcoin/blockchain_utils

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  flutter_lints: ^4.0.0
